on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: pawssier    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.4'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: actions/checkout@v3

    - name: Azure CLI script to access key vault
      id: petfinderApiKey
      uses: azure/CLI@v1
      with:
        azcliversion: 2.45.0
        inlineScript: |
          echo "petfinderApiKey=$(az keyvault secret show --name petfinderApiKey --vault-name kv-pawssier --query value -o tsv)" >> $GITHUB_ENV
          echo "petfinderApiSecret=$(az keyvault secret show --name petfinderApiSecret --vault-name kv-pawssier --query value -o tsv)" >> $GITHUB_ENV
          
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install and build
      run: npm install && npm run build --if-present
      env:
        petfinderApiKey: ${{ env.petfinderApiKey }}
        petfinderApiSecret: ${{ env.petfinderApiSecret }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./dist/bootcamp-project

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
